/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';
import ButtonGroup from '../packages/button-group/index.js';

const components = [
  Button,
  ButtonGroup
];
  
const install = function(Vue) {
    components.forEach(component => {
        Vue.component(component.name, component);
    });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
}

export default {
  version: '1.0.0',
  install,
  Button,
  ButtonGroup
};